#Stage 1: Build the React application
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

#Stage 2: Serve the React application using Nginx
FROM nginx:alpine
#Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*
#Copy static assets from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]